server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/my_date_base
    username: postgres
    password: bobik_sharik_23
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  jackson:
    deserialization:
      fail-on-unknown-properties: true